# Generated by Django 4.2.6 on 2024-01-18 08:12

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Gambar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.dashboard.models.file_image, verbose_name='Photo'),
        ),
    ]
